
import React from 'react';
import Section from './common/Section';
import Card from './common/Card';
import { SparklesIcon, CheckBadgeIcon, SignalSlashIcon, BookOpenIcon } from '../constants';

const featuresData = [
  {
    icon: <SparklesIcon />,
    title: 'AI-Powered Explanations',
    description: 'Curious about a topic? Get concise, easy-to-understand explanations generated by advanced Gemini AI, sent directly to your SMS.',
  },
  {
    icon: <CheckBadgeIcon />,
    title: 'Interactive Quizzes',
    description: 'Test your knowledge in Science, Math, and History with engaging quizzes. AI crafts the questions for you to answer via USSD.',
  },
  {
    icon: <SignalSlashIcon />,
    title: 'Learn Offline',
    description: 'No internet? No problem! SuperiaTech works on any mobile phone, making education accessible even in remote areas.',
  },
  {
    icon: <BookOpenIcon />,
    title: 'Bite-Sized Learning',
    description: 'Perfect for learning on the go. Information is delivered in short, digestible SMS messages, fitting into your busy schedule.',
  },
];

const Features: React.FC = () => {
  return (
    <Section id="features" title="Why Choose SuperiaTech Learning?" className="bg-light">
      <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-8">
        {featuresData.map((feature, index) => (
          <Card
            key={index}
            icon={feature.icon}
            title={feature.title}
            description={feature.description}
          />
        ))}
      </div>
    </Section>
  );
};

export default Features;
    